### ISSUE TITLE
Default sensor is not supported

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/TemperatureMonitoring#11]
Following the guide, doing a clean build with the only published recommended sensor, doesn't work at all. 

It's hard see exactly how we got here because release v1.1.2 wasn't made from the default branch of the repo ... grrr.
It looks like a simple installation of the sensor library issue, but I can't believe that the University would publish something that doesn't work. I will assume instead that a recent update to an external repo (Raspberry Pi OS or w1thermsensor etc) has broken code that used to work. 

This is reproducible on the repo's default branch `master` (@ 666211f577a197673641bc9525dc01bb91ccaca1) and at the latest release, which the guide points to, tag `v1.1.2` (afe927504df885ba8846298500632ec390579d3e) 

The issue reported in docker-temperature-dc.log is to the tune of:
```
Traceback (most recent call last):
   File "/app/main.py", line 41, in <module>
     import measure
   File "/app/measure.py", line 40, in <module>
     import sensor_select as sen
   File "/app/sensor_select.py", line 5, in <module>
     from w1thermsensor import W1ThermSensor
   File "/usr/local/lib/python3.12/site-packages/w1thermsensor/__init__.py", line 38, in <module>
     load_kernel_modules()
   File "/usr/local/lib/python3.12/site-packages/w1thermsensor/kernel.py", line 40, in load_kernel_modules
     raise KernelModuleLoadError()
w1thermsensor.errors.KernelModuleLoadError: Cannot load w1 therm kernel modules
```

In any case - how do we fix it?

**Comment by tobyaharris** [comment]
It is relevant that the dependency on w1thermsensor in `temperature_dc/requirements.txt` does not have a version stated. However, testing of explicitly adding the version tag `==2.0.0` , see branch `bugfix/explicit-versions` has not resolved the issue
